### ISSUE TITLE
acara

### ISSUE THREAD

**Issue by zzul** [SyaddadDeveloper/Volunter-Pembuatan-Aplikasi#2]
Ini sebenarnya acara apa sih bang? Kok rame banget yg bikin repo kek gini

**Comment by SyaddadDeveloper** [comment]
MBKM (merdeka belajar kampus merdeka) ada program bangkit academy yang maternya berasal dari kelas dicoding salahsatu tugasnya adalah untuk menjadi kolaborator di repo ini dengan menambahkan informasi diri (exp: linkedin)
